"""
Soma Clinical Record — PDF Export
Renders a multi-page clinical document from Oura biometric data.
Uses Playwright to convert styled HTML to PDF.
"""

import statistics
from datetime import date, timedelta
from pathlib import Path


def _mean(vals):
    valid = [v for v in vals if v is not None]
    return round(sum(valid) / len(valid), 1) if valid else None


def _trend_arrow(vals):
    """Return trend direction from last 7 values."""
    recent = [v for v in vals[-7:] if v is not None]
    if len(recent) < 3:
        return ""
    first_half = _mean(recent[: len(recent) // 2])
    second_half = _mean(recent[len(recent) // 2 :])
    if first_half is None or second_half is None:
        return ""
    diff = second_half - first_half
    if diff > 2:
        return "&#8593;"  # up arrow
    if diff < -2:
        return "&#8595;"  # down arrow
    return "&#8594;"  # right arrow (stable)


def _svg_trend(values, width=460, height=80):
    """Generate a simple SVG trend line for the PDF."""
    pts = [(i, v) for i, v in enumerate(values) if v is not None]
    if len(pts) < 2:
        return '<div style="height:80px;color:#8B7F75;font-size:11px;">Insufficient data</div>'

    vals = [v for _, v in pts]
    vmin = min(vals) - 2
    vmax = max(vals) + 2
    vrange = vmax - vmin or 1
    avg = sum(vals) / len(vals)

    pad_l, pad_r, pad_t, pad_b = 4, 4, 8, 8
    cw = width - pad_l - pad_r
    ch = height - pad_t - pad_b

    def x(i):
        return pad_l + i * cw / (len(values) - 1)

    def y(v):
        return pad_t + (vmax - v) * ch / vrange

    base_y = y(avg)

    svg = f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:{height}px;">'
    # Baseline
    svg += f'<line x1="{pad_l}" y1="{base_y:.1f}" x2="{width - pad_r}" y2="{base_y:.1f}" stroke="#E8DFD5" stroke-width="1" stroke-dasharray="3 3"/>'
    # avg label
    svg += f'<text x="{width - pad_r}" y="{base_y - 4:.1f}" text-anchor="end" fill="#8B7F75" font-family="JetBrains Mono,monospace" font-size="8">avg {round(avg)}</text>'

    # Line
    path_d = " ".join(
        f"{'M' if j == 0 else 'L'}{x(i):.1f},{y(v):.1f}" for j, (i, v) in enumerate(pts)
    )
    svg += f'<path d="{path_d}" stroke="#1A1613" stroke-width="1.2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>'

    # Last dot
    last_i, last_v = pts[-1]
    svg += f'<circle cx="{x(last_i):.1f}" cy="{y(last_v):.1f}" r="3" fill="#6B1E1E"/>'

    svg += "</svg>"
    return svg


def _build_html(data: dict, cycle_info: dict = None) -> str:
    """Build the full multi-page HTML document for PDF rendering."""
    keys = sorted(data.keys())[-30:]
    if not keys:
        return "<html><body><p>No data available.</p></body></html>"

    date_start = keys[0]
    date_end = keys[-1]
    today_str = str(date.today())

    # Collect signal arrays
    sleep = [data[k].get("sleep_score") for k in keys]
    hrv = [data[k].get("hrv_balance") for k in keys]
    readiness = [data[k].get("readiness_score") for k in keys]
    deep = [data[k].get("deep_sleep_score") for k in keys]
    body_temp = [data[k].get("body_temperature_score") for k in keys]
    efficiency = [data[k].get("efficiency_score") for k in keys]
    steps = [data[k].get("steps") for k in keys]

    # Summary stats
    def _stats(vals):
        valid = [v for v in vals if v is not None]
        if not valid:
            return {"mean": "—", "min": "—", "max": "—", "sd": "—", "n": 0}
        m = round(sum(valid) / len(valid), 1)
        sd = round(statistics.stdev(valid), 1) if len(valid) >= 2 else 0
        return {"mean": m, "min": min(valid), "max": max(valid), "sd": sd, "n": len(valid)}

    sleep_s = _stats(sleep)
    hrv_s = _stats(hrv)
    readiness_s = _stats(readiness)
    deep_s = _stats(deep)
    temp_s = _stats(body_temp)

    # Date labels for chart x-axes
    date_labels = [keys[0], keys[len(keys) // 2], keys[-1]]

    # Cycle section
    cycle_html = _build_cycle_section(cycle_info, data, keys)

    pages = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
@import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=Inter+Tight:wght@400;500&family=JetBrains+Mono:wght@400;500&display=swap');

@page {{
  size: A4;
  margin: 28mm 24mm 32mm 24mm;
  @bottom-center {{
    content: "Generated by Soma. For clinical use.";
    font-family: 'Inter Tight', sans-serif;
    font-size: 8px;
    color: #8B7F75;
  }}
  @bottom-right {{
    content: counter(page) " / " counter(pages);
    font-family: 'JetBrains Mono', monospace;
    font-size: 8px;
    color: #8B7F75;
  }}
}}

* {{ box-sizing: border-box; margin: 0; padding: 0; }}

body {{
  font-family: 'Inter Tight', sans-serif;
  font-size: 10pt;
  line-height: 1.5;
  color: #1A1613;
}}

.page-break {{ page-break-after: always; }}

/* Cover */
.cover {{
  display: flex;
  flex-direction: column;
  justify-content: center;
  min-height: 680px;
}}
.cover-label {{
  font-family: 'JetBrains Mono', monospace;
  font-size: 8pt;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: #8B7F75;
  margin-bottom: 12px;
}}
.cover-title {{
  font-family: 'Fraunces', serif;
  font-size: 28pt;
  font-weight: 500;
  line-height: 1.15;
  margin-bottom: 20px;
  color: #1A1613;
}}
.cover-meta {{
  font-family: 'Inter Tight', sans-serif;
  font-size: 10pt;
  color: #8B7F75;
  line-height: 1.8;
}}
.cover-footer {{
  margin-top: auto;
  padding-top: 40px;
  font-family: 'JetBrains Mono', monospace;
  font-size: 7pt;
  color: #8B7F75;
  letter-spacing: 0.06em;
}}
.cover-divider {{
  width: 48px;
  height: 2px;
  background: #6B1E1E;
  margin: 24px 0;
}}

/* Section headers */
.section-title {{
  font-family: 'Fraunces', serif;
  font-size: 16pt;
  font-weight: 500;
  margin-bottom: 6px;
  color: #1A1613;
}}
.section-subtitle {{
  font-family: 'JetBrains Mono', monospace;
  font-size: 7pt;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color: #8B7F75;
  margin-bottom: 20px;
}}

/* Summary table */
.summary-table {{
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 24px;
}}
.summary-table th {{
  font-family: 'JetBrains Mono', monospace;
  font-size: 7pt;
  font-weight: 500;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: #8B7F75;
  text-align: left;
  padding: 0 8px 6px 0;
  border-bottom: 1px solid #E8DFD5;
}}
.summary-table th:not(:first-child) {{ text-align: right; padding-right: 12px; }}
.summary-table td {{
  font-size: 9pt;
  padding: 6px 8px 6px 0;
  border-bottom: 1px solid #F0EAE0;
  vertical-align: middle;
}}
.summary-table td:not(:first-child) {{
  text-align: right;
  font-family: 'JetBrains Mono', monospace;
  font-size: 8pt;
  padding-right: 12px;
}}
.summary-table td:first-child {{ font-weight: 500; }}
.summary-table tr:last-child td {{ border-bottom: none; }}

/* Chart block */
.chart-block {{
  margin-bottom: 20px;
}}
.chart-label {{
  font-family: 'JetBrains Mono', monospace;
  font-size: 7pt;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: #8B7F75;
  margin-bottom: 4px;
}}
.chart-dates {{
  display: flex;
  justify-content: space-between;
  font-family: 'JetBrains Mono', monospace;
  font-size: 7pt;
  color: #8B7F75;
  margin-top: 2px;
}}

/* Cycle */
.phase-bar {{
  display: flex;
  height: 24px;
  border-radius: 3px;
  overflow: hidden;
  margin-bottom: 8px;
}}
.phase-seg {{
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: 'JetBrains Mono', monospace;
  font-size: 7pt;
  letter-spacing: 0.04em;
  color: white;
}}
.phase-menstrual {{ background: #6B1E1E; }}
.phase-follicular {{ background: #2D4A3A; }}
.phase-ovulatory {{ background: #A0691E; }}
.phase-luteal {{ background: #8B7F75; }}
.phase-late_luteal {{ background: #6B5F55; }}
.phase-legend {{
  display: flex;
  gap: 16px;
  margin-bottom: 20px;
}}
.phase-legend-item {{
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 8pt;
  color: #8B7F75;
}}
.phase-dot {{
  width: 8px;
  height: 8px;
  border-radius: 2px;
}}

/* Placeholder */
.placeholder {{
  padding: 40px 0;
  text-align: center;
  color: #8B7F75;
  font-size: 10pt;
  font-style: italic;
  border: 1px dashed #E8DFD5;
  border-radius: 4px;
  margin: 20px 0;
}}
.placeholder-label {{
  font-family: 'JetBrains Mono', monospace;
  font-size: 7pt;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  margin-bottom: 8px;
  font-style: normal;
}}

/* Notes lines */
.note-lines {{
  margin-top: 20px;
}}
.note-line {{
  border-bottom: 1px solid #F0EAE0;
  height: 32px;
}}
</style>
</head>
<body>

<!-- PAGE 1: COVER -->
<div class="cover">
  <div class="cover-label">Soma Clinical Record</div>
  <div class="cover-divider"></div>
  <div class="cover-title">Biometric &amp;<br>Wellness Summary</div>
  <div class="cover-meta">
    Date range: {_fmt_date(date_start)} &ndash; {_fmt_date(date_end)}<br>
    Days covered: {len(keys)}<br>
    Generated: {_fmt_date(today_str)}
  </div>
  <div class="cover-footer">
    This document contains biometric data collected via Oura Ring.<br>
    It is intended to support clinical review and does not constitute medical advice.
  </div>
</div>
<div class="page-break"></div>

<!-- PAGE 2: BIOMETRIC SUMMARY -->
<div class="section-title">Biometric Summary</div>
<div class="section-subtitle">{_fmt_date(date_start)} &ndash; {_fmt_date(date_end)} &middot; {len(keys)} days</div>

<table class="summary-table">
  <thead>
    <tr>
      <th>Signal</th>
      <th>Mean</th>
      <th>Min</th>
      <th>Max</th>
      <th>SD</th>
      <th>Trend</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>Sleep score</td><td>{sleep_s['mean']}</td><td>{sleep_s['min']}</td><td>{sleep_s['max']}</td><td>{sleep_s['sd']}</td><td>{_trend_arrow(sleep)}</td></tr>
    <tr><td>HRV balance</td><td>{hrv_s['mean']}</td><td>{hrv_s['min']}</td><td>{hrv_s['max']}</td><td>{hrv_s['sd']}</td><td>{_trend_arrow(hrv)}</td></tr>
    <tr><td>Readiness</td><td>{readiness_s['mean']}</td><td>{readiness_s['min']}</td><td>{readiness_s['max']}</td><td>{readiness_s['sd']}</td><td>{_trend_arrow(readiness)}</td></tr>
    <tr><td>Deep sleep</td><td>{deep_s['mean']}</td><td>{deep_s['min']}</td><td>{deep_s['max']}</td><td>{deep_s['sd']}</td><td>{_trend_arrow(deep)}</td></tr>
    <tr><td>Body temperature</td><td>{temp_s['mean']}</td><td>{temp_s['min']}</td><td>{temp_s['max']}</td><td>{temp_s['sd']}</td><td>{_trend_arrow(body_temp)}</td></tr>
  </tbody>
</table>

<div class="chart-block">
  <div class="chart-label">Sleep score</div>
  {_svg_trend(sleep)}
  <div class="chart-dates"><span>{_fmt_date_short(date_start)}</span><span>{_fmt_date_short(keys[len(keys)//2])}</span><span>{_fmt_date_short(date_end)}</span></div>
</div>

<div class="chart-block">
  <div class="chart-label">HRV balance</div>
  {_svg_trend(hrv)}
  <div class="chart-dates"><span>{_fmt_date_short(date_start)}</span><span>{_fmt_date_short(keys[len(keys)//2])}</span><span>{_fmt_date_short(date_end)}</span></div>
</div>

<div class="chart-block">
  <div class="chart-label">Readiness</div>
  {_svg_trend(readiness)}
  <div class="chart-dates"><span>{_fmt_date_short(date_start)}</span><span>{_fmt_date_short(keys[len(keys)//2])}</span><span>{_fmt_date_short(date_end)}</span></div>
</div>

<div class="chart-block">
  <div class="chart-label">Deep sleep</div>
  {_svg_trend(deep)}
  <div class="chart-dates"><span>{_fmt_date_short(date_start)}</span><span>{_fmt_date_short(keys[len(keys)//2])}</span><span>{_fmt_date_short(date_end)}</span></div>
</div>

<div class="chart-block">
  <div class="chart-label">Body temperature</div>
  {_svg_trend(body_temp)}
  <div class="chart-dates"><span>{_fmt_date_short(date_start)}</span><span>{_fmt_date_short(keys[len(keys)//2])}</span><span>{_fmt_date_short(date_end)}</span></div>
</div>

<div class="page-break"></div>

<!-- PAGE 3: CYCLE HISTORY -->
<div class="section-title">Cycle History</div>
<div class="section-subtitle">Phase distribution and observations</div>
{cycle_html}

<div class="page-break"></div>

<!-- PAGE 4: LAB DATA -->
<div class="section-title">Lab Data</div>
<div class="section-subtitle">Blood work &amp; diagnostics</div>
<div class="placeholder">
  <div class="placeholder-label">No lab data uploaded</div>
  Lab results can be uploaded through the Soma app.<br>
  Future versions will integrate with major lab providers.
</div>

<div class="page-break"></div>

<!-- PAGE 5: CLINICIAN NOTES -->
<div class="section-title">Clinician Notes</div>
<div class="section-subtitle">For use during consultation</div>
<div class="note-lines">
  {"".join('<div class="note-line"></div>' for _ in range(20))}
</div>

</body>
</html>"""

    return pages


def _build_cycle_section(cycle_info: dict, data: dict, keys: list) -> str:
    """Build the cycle history HTML section."""
    if not cycle_info:
        return """<div class="placeholder">
          <div class="placeholder-label">No cycle data logged</div>
          Cycle tracking can be enabled in the Soma app.<br>
          Phase-aware insights appear after logging two or more cycles.
        </div>"""

    phase = cycle_info.get("phase", "unknown")
    day = cycle_info.get("day_of_cycle", "—")
    avg_len = cycle_info.get("average_length", 28)
    predicted = cycle_info.get("predicted_next_start", "—")

    # Phase distribution bar
    phases_def = [
        ("menstrual", "Menstrual", 5),
        ("follicular", "Follicular", 8),
        ("ovulatory", "Ovulatory", 3),
        ("luteal", "Luteal", max(avg_len - 20, 6)),
        ("late_luteal", "Late luteal", 4),
    ]
    total = sum(d for _, _, d in phases_def)
    bar_html = '<div class="phase-bar">'
    for pid, plabel, pdays in phases_def:
        pct = pdays / total * 100
        bar_html += f'<div class="phase-seg phase-{pid}" style="flex:{pct:.1f}">{plabel}</div>'
    bar_html += "</div>"

    legend_html = '<div class="phase-legend">'
    colors = {"menstrual": "#6B1E1E", "follicular": "#2D4A3A", "ovulatory": "#A0691E", "luteal": "#8B7F75", "late_luteal": "#6B5F55"}
    for pid, plabel, pdays in phases_def:
        legend_html += f'<div class="phase-legend-item"><div class="phase-dot" style="background:{colors[pid]}"></div>{plabel} ({pdays}d)</div>'
    legend_html += "</div>"

    pattern_obs = cycle_info.get("pattern_observation", "")
    pattern_html = ""
    if pattern_obs:
        pattern_html = f'<p style="font-size:9pt;color:#1A1613;margin-top:16px;line-height:1.6;">{pattern_obs}</p>'

    return f"""
    <table class="summary-table" style="max-width:340px;margin-bottom:20px;">
      <tbody>
        <tr><td>Current phase</td><td>{phase.replace('_',' ').title()}</td></tr>
        <tr><td>Cycle day</td><td>{day}</td></tr>
        <tr><td>Average length</td><td>{avg_len} days</td></tr>
        <tr><td>Predicted next</td><td>{_fmt_date(predicted) if predicted != '—' else '—'}</td></tr>
      </tbody>
    </table>
    {bar_html}
    {legend_html}
    {pattern_html}
    <p style="font-size:8pt;color:#8B7F75;margin-top:12px;">
      Symptom logging is not yet available. Future versions will display logged symptoms alongside phase data.
    </p>
    """


def _fmt_date(date_str: str) -> str:
    """Format date string to '7 May 2026'."""
    try:
        d = date.fromisoformat(date_str)
        months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        return f"{d.day} {months[d.month - 1]} {d.year}"
    except (ValueError, TypeError):
        return str(date_str)


def _fmt_date_short(date_str: str) -> str:
    """Format date to '7/5'."""
    try:
        d = date.fromisoformat(date_str)
        return f"{d.day}/{d.month}"
    except (ValueError, TypeError):
        return str(date_str)


async def generate_pdf(data: dict, cycle_info: dict = None) -> bytes:
    """Generate the clinical record PDF. Returns raw PDF bytes."""
    from playwright.async_api import async_playwright

    html = _build_html(data, cycle_info)

    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        await page.set_content(html, wait_until="networkidle")
        pdf_bytes = await page.pdf(
            format="A4",
            margin={"top": "28mm", "right": "24mm", "bottom": "32mm", "left": "24mm"},
            print_background=True,
            display_header_footer=True,
            header_template='<span></span>',
            footer_template="""
                <div style="width:100%;font-family:sans-serif;font-size:8px;color:#8B7F75;display:flex;justify-content:space-between;padding:0 24mm;">
                    <span>Generated by Soma. For clinical use.</span>
                    <span><span class="pageNumber"></span> / <span class="totalPages"></span></span>
                </div>
            """,
        )
        await browser.close()

    return pdf_bytes
